kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: build
    privileged: true
    image: docker/compose:1.26.0
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.yml build --no-cache
    depends_on:
      - fetch

  - name: publish_dockerhub
    image: plugins/docker
    when:
      event: tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: acidann/locksley
      tags:
        - latest
        - ${DRONE_TAG}
    depends_on:
      - build

  - name: publish_github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_release_token
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
    depends_on:
      - build

  - name: send telegram notification
    image: appleboy/drone-telegram
    when:
      status:
        - success
        - failure
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
    depends_on:
      - publish_dockerhub
      - publish_github

trigger:
  event:
    - push
    - tag

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
