version: "3.8"

networks:
  pg_db:
    internal: true

services:
  annotation:
    image: locksley
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
      - pg_db
    volumes:
      - ./django_unchained:/annotation
    env_file:
      - sample.env
    ports:
      - 8080:80
    depends_on:
      - dbannotation

  dbannotation:
    image: postgres:12.3-alpine
    networks:
      - pg_db
    volumes:
      - ../databases:/var/lib/postgresql/data/
    env_file:
      - sample.env