#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'deluge==2.0.4.dev23','console_scripts','deluge-web'
__requires__ = 'deluge==2.0.4.dev23'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('deluge==2.0.4.dev23', 'console_scripts', 'deluge-web')()
    )
