# Generated by Django 3.0.6 on 2020-05-31 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('yummy', 'Leibspeise'), ('eddi', 'Lieblingseditor'), ('enemy', 'Todfeind'), ('other', 'Keine Relation')], max_length=500)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Sentence')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
