# Generated by Django 3.0.6 on 2020-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="number_of_labeled_sentences",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="batch",
            name="number_of_sentences",
            field=models.IntegerField(default=0),
        ),
    ]
