# Generated by Django 3.0.6 on 2020-05-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('sentence', 'user', 'relation_type')},
        ),
    ]
