# Generated by Django 3.0.6 on 2020-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0002_auto_20200602_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="percentage_labeled",
            field=models.IntegerField(default=0),
        ),
    ]
