# Generated by Django 3.0.6 on 2020-05-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20200531_2032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('sentence', 'user')},
        ),
    ]
