# Generated by Django 3.0.6 on 2020-06-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_batch_percentage_labeled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
    ]
