# Generated by Django 3.0.6 on 2020-06-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20200627_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplesentence',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='entities',
        ),
        migrations.AddField(
            model_name='entity',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.Sentence'),
        ),
        migrations.CreateModel(
            name='ExampleEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(default='', max_length=500)),
                ('example_sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.ExampleSentence')),
            ],
        ),
        migrations.AlterField(
            model_name='goldlabel',
            name='goldentity1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goldentity1', to='annotation.ExampleEntity'),
        ),
        migrations.AlterField(
            model_name='goldlabel',
            name='goldentity2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goldentity2', to='annotation.ExampleEntity'),
        ),
    ]
