# Generated by Django 3.0.6 on 2020-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20200628_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='number_of_example_sentences',
        ),
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='tag_line',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='example1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='example2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='example3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='example4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='example5',
            field=models.CharField(max_length=1000),
        ),
    ]
