# Generated by Django 3.0.6 on 2020-06-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20200602_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='corpus',
        ),
        migrations.AddField(
            model_name='sentence',
            name='corpus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.Corpus'),
        ),
    ]
