# Generated by Django 3.0.6 on 2020-06-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_auto_20200629_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='number_of_sentences',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='percentage_labeled',
        ),
    ]
