# Generated by Django 3.0.6 on 2020-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_auto_20200629_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='group',
            field=models.CharField(default='', max_length=500),
        ),
    ]
