# Generated by Django 3.0.6 on 2020-06-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_batch_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldlabel',
            old_name='goldrelation_type',
            new_name='gold_relation_type',
        ),
        migrations.RemoveField(
            model_name='goldlabel',
            name='goldentity1',
        ),
        migrations.RemoveField(
            model_name='goldlabel',
            name='goldentity2',
        ),
        migrations.AddField(
            model_name='goldlabel',
            name='gold_entity1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gold_entity1', to='annotation.ExampleEntity'),
        ),
        migrations.AddField(
            model_name='goldlabel',
            name='gold_entity2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gold_entity2', to='annotation.ExampleEntity'),
        ),
    ]
